- name: "Kamina"
  image: "/static/avatars/kamina.png"
  categories: ["study", "system_design", "motivation"]
  quotes:
    - "Believe in the you who believes in yourself!"
    - "PRCANJE I ROK RADIO!"
    - "Rok Radio jebe mame kurve"
    - "Ko napuni ove lignje usrane?"

- name: "Saitama"
  image: "/static/avatars/saitama.png"
  categories: ["leetcode", "efficiency"]
  quotes:
    - "Do it once. Do it right. Then relax."
    - "You're overthinking it. Just solve it."
    - "MIHAJLOO OO O OO O  O OOOO"
    - "Je li,\n ko napuni ove lignje?"

- name: "Goku"
  image: "/static/avatars/goku.png"
  categories: ["growth", "progress", "learning"]
  quotes:
    - "Mozes da izvedeš čoveka iz Borče, al ne i Borču iz čoveka"
    - "HASAAAA"
    - "KAIOKEN    TIMES    THREEEE"

- name: "Master Roshi"
  image: "/static/avatars/roshi.png"
  categories: ["habits", "discipline", "lifestyle"]
  quotes:
    - "I have many things... a best friend who's a turtle, and island, chlamydia... this is not one of them..."
    - "MAJSTORE, ZADNJA"
    - "Mali, ae diži se da smestim Kosti"
